#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"
# prompts: oh-my-bash sexy theme puts "user at host in dir" above "$ cmd";
# bash default is "user@host:dir$ cmd"
export header="^$(whoami) at $(hostname -s) "
export uhost='^[^ ]+@[^ ]+:[^ ]*[$#]'
chosen="$(awk '
	h && /^[$#] +[^ ]/ || $0 ~ ENVIRON["uhost"] " +[^ ]" { print }
	{ h = ($0 ~ ENVIRON["header"]) }
' "$tmpfile" | tac | dmenu -p "Copy which command's output?" -i -l 10)"
[ -n "$chosen" ] || exit
# the most recent run of the chosen command, up to the next prompt
chosen="$chosen" awk '
	$0 == ENVIRON["chosen"] { buf = $0; f = 1; next }
	f && ($0 ~ ENVIRON["header"] || $0 ~ ENVIRON["uhost"]) { f = 0; out = buf }
	f { buf = buf "\n" $0 }
	END { print (f ? buf : out) }
' "$tmpfile" | xclip -selection clipboard
